service: qlik-sudoku-challenge-v1
provider:
  name: aws
  runtime: nodejs6.10
  profile: karthik
  region: us-east-1
  environment:
    TABLE_NAME: sudokuPuzzles
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource:
          Fn::Join:
            - ":"
            - - "arn:aws:dynamodb"
              - Ref: "AWS::Region"
              - Ref: "AWS::AccountId"
              - "table/sudokuPuzzles"
functions:
  solveSudoku:
     handler: index.solveSudokuPuzzle
     memorySize: 128
     events:
       - http:
           path: sudoku
           method: post
     description: 'Returns solved sudoku puzzle'
  showSudoku:
    handler: index.showSudokuPuzzles
    memorySize: 128
    events:
      - http:
          path: sudoku/random
          method: get
    description: 'Returns a bunch of sudoku puzzles from db'